server:
  port: 8081
  servlet:
    encoding:
      # 한글깨짐 처리 
      force-response: true

# Spring Data Source 설정 
spring:
  profiles:
    active: dev  # default application 파일의 이름
                 # ex application-dev.yml -> dev

# spring doc
springdoc:
  show-login-endpoint: true # security /login 적용 
  api-docs:
    path: /api-docs
    groups:
      enabled: true
  swagger-ui:
    path: /swagger-ui-custom.html
    enabled: true
    groups-order: ASC
    tags-sorter: alpha
    operations-sorter: alpha
    display-request-duration: true
    doc-expansion: none
  cache:
    disabled: true
  model-and-view-allowed: true


# loging
# race → warn → info → debug → error(적은 로깅) 순
# 개발 서버는 debug, 운영 서버는 info
logging:
  level:
    com.web: debug